radioStar/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :songs
  resources :stations do
    resources :users do
       resources :shows do
         resources :playlists do
           resources :songs
         end
       end
       resources :user_shows
    end
    resources :charts do
      resources :songs
    end
    resources :shows do
        resources :user_shows
    end
  end

  root "profile#index"

  get 'profile/index'
  get 'manage', to: 'manage#index', as: "manage"
  post 'profile/radioactivity_login', to: 'profile#radioactivity_login'
  post 'profile/radioactivity_get_songs', to: 'profile#radioactivity_get_songs'

end

radioStar/app/models/playlist.rb
class Playlist < ActiveRecord::Base
  belongs_to :show
  has_many :songs, dependent: :destroy

end

radioStar/app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :edit, :update, :destroy]
  respond_to :json

  # GET /playlists
  # GET /playlists.json
  def index
    @playlists = Playlist.all
    respond_with @playlists
  end

  # GET /playlists/1
  # GET /playlists/1.json
  def show
    respond_with @playlist
  end

  # GET /playlists/new
  def new
    @playlist = Playlist.new
  end

  # GET /playlists/1/edit
  def edit
  end

  # POST /playlists
  # POST /playlists.json
  def create
    @playlist = Playlist.new(playlist_params)

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to root_url, notice: 'Playlist was successfully created.' }
        format.json { render :show, status: :created, location: @playlist }
      else
        format.html { render :new }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playlists/1
  # PATCH/PUT /playlists/1.json
  def update
    respond_to do |format|
      if @playlist.update(playlist_params)
        format.html { redirect_to root_url, notice: 'Playlist was successfully updated.' }
        format.json { render :show, status: :ok, location: @playlist }
      else
        format.html { render :edit }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1
  # DELETE /playlists/1.json
  def destroy
    @playlist.destroy
    respond_to do |format|
      if @playlist.show_id
        format.html { redirect_to show_url(@playlist.show_id), notice: 'Playlist was successfully destroyed.' }
      else
        format.html { redirect_to chart_url(@playlist.chart_id), notice: 'Playlist was successfully destroyed.' }
      end
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playlist
      @playlist = Playlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def playlist_params
      params.require(:playlist).permit(:show_id, :chart_id, :playlist_id, :date)
    end
end

radioStar/app/helpers/playlists_helper.rb
module PlaylistsHelper
end

radioStar/app/views/playlists/_form.html.erb
<%= form_for(@playlist) do |f| %>
  <% if @playlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>

      <ul>
      <% @playlist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :show_id %><br>
    <%= f.number_field :show_id %>
  </div>
  <div class="field">
    <%= f.label :chart_id %><br>
    <%= f.number_field :chart_id %>
  </div>
  <div class="field">
    <%= f.label :playlist_id %><br>
    <%= f.number_field :playlist_id %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

radioStar/app/views/playlists/edit.html.erb
<h1>Editing Playlist</h1>

<%= render 'form' %>

<%= link_to 'Show', @playlist %> |
<%= link_to 'Back', playlists_path %>

radioStar/app/views/playlists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Playlists</h1>

<table>
  <thead>
    <tr>
      <th>Show</th>
      <th>Chart</th>
      <th>Playlist</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @playlists.each do |playlist| %>
      <tr>
        <td><%= playlist.show_id %></td>
        <td><%= playlist.chart_id %></td>
        <td><%= playlist.playlist_id %></td>
        <td><%= playlist.date %></td>
        <td><%= link_to 'Show', playlist %></td>
        <td><%= link_to 'Edit', edit_playlist_path(playlist) %></td>
        <td><%= link_to 'Destroy', playlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Playlist', new_playlist_path %>

radioStar/app/views/playlists/new.html.erb
<h1>New Playlist</h1>

<%= render 'form' %>

<%= link_to 'Back', playlists_path %>

radioStar/app/views/playlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Show:</strong>
  <%= @playlist.show_id %>
</p>

<p>
  <strong>Chart:</strong>
  <%= @playlist.chart_id %>
</p>

<p>
  <strong>Playlist:</strong>
  <%= @playlist.playlist_id %>
</p>

<p>
  <strong>Date:</strong>
  <%= @playlist.date %>
</p>

<%= link_to 'Edit', edit_playlist_path(@playlist) %> |
<%= link_to 'Back', playlists_path %>