radioStar/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :songs
  resources :stations do
    resources :users do
       resources :shows do
         resources :playlists do
           resources :songs
         end
       end
       resources :user_shows
    end
    resources :charts do
      resources :songs
    end
    resources :shows do
        resources :user_shows
    end
  end

  root "profile#index"

  get 'profile/index'
  get 'manage', to: 'manage#index', as: "manage"
  post 'profile/radioactivity_login', to: 'profile#radioactivity_login'
  post 'profile/radioactivity_get_songs', to: 'profile#radioactivity_get_songs'

end

radioStar/app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :chart
  belongs_to :playlist

  # validates :title, :presence => true
  # validates :artist, :presence => true

end

radioStar/app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]
  respond_to :json

  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all
    respond_with @songs
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
    respond_with @song
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to root_url, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to root_url, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:playlist_id, :title, :artist, :album, :label, :genre, :time)
    end
end

radioStar/app/helpers/songs_helper.rb
module SongsHelper
end

radioStar/app/views/songs/_form.html.erb
<%= form_for (song) do |f| %>
  <% if song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% song.errors.full_messages.each do |message| %>
        <div class="alert alert-danger">
          <li><%= message %></li>
        </div>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :playlist_id, :readonly => true %>
  </div>
    <div class="col-xs-4">
      <%= f.label :title %>
      <%= f.text_field :title, :class => "form-control"%>
    </div>
    <div class="col-xs-4">
      <%= f.label :artist %>
      <%= f.text_field :artist, :class => "form-control" %>
    </div>
  <div class="col-xs-4">
    <%= f.label :album %>
    <%= f.text_field :album, :class => "form-control" %>
  </div>
  <div class="col-xs-4">
    <%= f.label :label %>
    <%= f.text_field :label, :class => "form-control" %>
  </div>
  <div class="col-xs-4">
    <%= f.label :genre %>
    <%= f.text_field :genre, :class => "form-control", :placeholder => "EDM, Hip Hop, etc..." %>
  </div>
  <div class="col-xs-8">
    <%= f.label :time %><br>
    <%= f.datetime_select :time %>
  </div>
  <div class="actions col-xs-4">
    <%= f.button :submit => 'Create', :remote => true, :class => "btn btn-default btn-md"%>
  </div>
<% end %>

radioStar/app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

radioStar/app/views/songs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Songs</h1>

<table>
  <thead>
    <tr>
      <th>Playlist</th>
      <th>Title</th>
      <th>Artist</th>
      <th>Album</th>
      <th>Label</th>
      <th>Genre</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.playlist_id %></td>
        <td><%= song.title %></td>
        <td><%= song.artist %></td>
        <td><%= song.album %></td>
        <td><%= song.label %></td>
        <td><%= song.genre %></td>
        <td><%= song.time %></td>
        <td><%= link_to 'Show', song %></td>
        <td><%= link_to 'Edit', edit_song_path(song) %></td>
        <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Song', new_song_path %>

radioStar/app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

radioStar/app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Playlist:</strong>
  <%= @song.playlist_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @song.title %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @song.artist %>
</p>

<p>
  <strong>Album:</strong>
  <%= @song.album %>
</p>

<p>
  <strong>Label:</strong>
  <%= @song.label %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @song.genre %>
</p>

<p>
  <strong>Time:</strong>
  <%= @song.time %>
</p>

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %>