radioStar/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :songs
  resources :stations do
    resources :users do
       resources :shows do
         resources :playlists do
           resources :songs
         end
       end
       resources :user_shows
    end
    resources :charts do
      resources :songs
    end
    resources :shows do
        resources :user_shows
    end
  end

  root "profile#index"

  get 'profile/index'
  get 'manage', to: 'manage#index', as: "manage"
  post 'profile/radioactivity_login', to: 'profile#radioactivity_login'
  post 'profile/radioactivity_get_songs', to: 'profile#radioactivity_get_songs'

end

radioStar/app/models/chart.rb
class Chart < ActiveRecord::Base
  belongs_to :station
  has_many :songs, dependent: :destroy
end

radioStar/app/controllers/charts_controller.rb
class ChartsController < ApplicationController
  before_action :set_chart, only: [:show, :edit, :update, :destroy]
  respond_to :json

  # GET /charts
  # GET /charts.json
  def index
    @charts = Chart.all
    respond_with @charts
  end

  # GET /charts/1
  # GET /charts/1.json
  def show
    respond_with @chart
  end

  # GET /charts/new
  def new
    @chart = Chart.new
  end

  # GET /charts/1/edit
  def edit
  end

  # POST /charts
  # POST /charts.json
  def create
    @chart = Chart.new(chart_params)

    respond_to do |format|
      if @chart.save
        format.html { redirect_to @chart, notice: 'Chart was successfully created.' }
        format.json { render :show, status: :created, location: @chart }
      else
        format.html { render :new }
        format.json { render json: @chart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /charts/1
  # PATCH/PUT /charts/1.json
  def update
    respond_to do |format|
      if @chart.update(chart_params)
        format.html { redirect_to @chart, notice: 'Chart was successfully updated.' }
        format.json { render :show, status: :ok, location: @chart }
      else
        format.html { render :edit }
        format.json { render json: @chart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /charts/1
  # DELETE /charts/1.json
  def destroy
    @chart.destroy
    respond_to do |format|
      format.html { redirect_to station_url(@chart.station_id), notice: 'Chart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chart
      @chart = Chart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chart_params
      params.require(:chart).permit(:name, :country, :source_url, :date)
    end
end

radioStar/app/helpers/charts_helper.rb
module ChartsHelper
end

radioStar/app/views/charts/_form.html.erb
<%= form_for(@chart) do |f| %>
  <% if @chart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chart.errors.count, "error") %> prohibited this chart from being saved:</h2>

      <ul>
      <% @chart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :source_url %><br>
    <%= f.text_field :source_url %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

radioStar/app/views/charts/edit.html.erb
<h1>Editing Chart</h1>

<%= render 'form' %>

<%= link_to 'Show', @chart %> |
<%= link_to 'Back', charts_path %>

radioStar/app/views/charts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Charts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Country</th>
      <th>Source url</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @charts.each do |chart| %>
      <tr>
        <td><%= chart.name %></td>
        <td><%= chart.country %></td>
        <td><%= chart.source_url %></td>
        <td><%= chart.date %></td>
        <td><%= link_to 'Show', chart %></td>
        <td><%= link_to 'Edit', edit_chart_path(chart) %></td>
        <td><%= link_to 'Destroy', chart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Chart', new_chart_path %>

radioStar/app/views/charts/new.html.erb
<h1>New Chart</h1>

<%= render 'form' %>

<%= link_to 'Back', charts_path %>

radioStar/app/views/charts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @chart.name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @chart.country %>
</p>

<p>
  <strong>Source url:</strong>
  <%= @chart.source_url %>
</p>

<p>
  <strong>Date:</strong>
  <%= @chart.date %>
</p>

<%= link_to 'Edit', edit_chart_path(@chart) %> |
<%= link_to 'Back', charts_path %>