radioStar/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :songs
  resources :stations do
    resources :users do
       resources :shows do
         resources :playlists do
           resources :songs
         end
       end
       resources :user_shows
    end
    resources :charts do
      resources :songs
    end
    resources :shows do
        resources :user_shows
    end
  end

  root "profile#index"

  get 'profile/index'
  get 'manage', to: 'manage#index', as: "manage"
  post 'profile/radioactivity_login', to: 'profile#radioactivity_login'
  post 'profile/radioactivity_get_songs', to: 'profile#radioactivity_get_songs'

end

radioStar/app/models/user_show.rb
class UserShow < ActiveRecord::Base
  belongs_to :user
  belongs_to :show
  
end

radioStar/app/controllers/user_shows_controller.rb
class UserShowsController < ApplicationController
  before_action :set_user_show, only: [:show, :edit, :update, :destroy]
  respond_to :json

  # GET /user_shows
  # GET /user_shows.json
  def index
    @user_shows = UserShow.all
    @users = User.all
    @shows = Show.all
    respond_with @user_shows
  end

  # GET /user_shows/1
  # GET /user_shows/1.json
  def show
    respond_with @user_show
  end

  # GET /user_shows/new
  def new
    @user_show = UserShow.new
    @users = User.all
    @shows = Show.all
  end

  # GET /user_shows/1/edit
  def edit
  end

  # POST /user_shows
  # POST /user_shows.json
  def create
    @user_show = UserShow.new(user_show_params)

    respond_to do |format|
      if @user_show.save
        format.html { redirect_to show_url(@user_show.show_id), notice: 'User was added to Show.' }
        format.json { render :show, status: :created, location: @user_show }
      else
        format.html { render :new }
        format.json { render json: @user_show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_shows/1
  # PATCH/PUT /user_shows/1.json
  def update
    respond_to do |format|
      if @user_show.update(user_show_params)
        format.html { redirect_to show_url(@user_show.show_id), notice: 'Users for Show were successfully updated.' }
        format.json { render :show, status: :ok, location: @user_show }
      else
        format.html { render :edit }
        format.json { render json: @user_show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_shows/1
  # DELETE /user_shows/1.json
  def destroy
    @user_show.destroy
    respond_to do |format|
      format.html { redirect_to user_shows_url, notice: 'User show was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_show
      @user_show = UserShow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_show_params
      params.require(:user_show).permit(:show_id, :user_id)
    end
end

radioStar/app/helpers/user_shows_helper.rb
module UserShowsHelper
end

radioStar/app/views/user_shows/_form.html.erb
<%= form_for(@user_show) do |f| %>
  <% if @user_show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_show.errors.count, "error") %> prohibited this user_show from being saved:</h2>

      <ul>
      <% @user_show.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :show_id %><br>
    <%= f.number_field :show_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

radioStar/app/views/user_shows/edit.html.erb
<h1>Editing User Show</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_show %> |
<%= link_to 'Back', user_shows_path %>

radioStar/app/views/user_shows/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Shows</h1>

<table>
  <thead>
    <tr>
      <th>Show</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_shows.each do |user_show| %>
      <tr>
        <td><%= user_show.show_id %></td>
        <td><%= user_show.user_id %></td>
        <td><%= link_to 'Show', user_show %></td>
        <td><%= link_to 'Edit', edit_user_show_path(user_show) %></td>
        <td><%= link_to 'Destroy', user_show, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User show', new_user_show_path %>

radioStar/app/views/user_shows/new.html.erb
<h1>New User Show</h1>

<%= render 'form' %>

<%= link_to 'Back', user_shows_path %>

radioStar/app/views/user_shows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Show:</strong>
  <%= @user_show.show_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @user_show.user_id %>
</p>

<%= link_to 'Edit', edit_user_show_path(@user_show) %> |
<%= link_to 'Back', user_shows_path %>